import type { LanguageOption } from "../types/language.types";
import { getPublicAssetPath } from "../utils/getPublicAssetPath";

export const languageOptions: LanguageOption[] = [
  {
    country: "Italy",
    label: "Italy (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/italy.jfif"),
  },
  {
    country: "Australia",
    label: "Australia (AUD $)",
    currencyShort: "AUD $",
    flag: getPublicAssetPath("assets/pages/shopx/languages/australia.jfif"),
  },
  {
    country: "Austria",
    label: "Austria (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/austria.jfif"),
  },
  {
    country: "Belgium",
    label: "Belgium (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/belgium.jfif"),
  },
  {
    country: "Bulgaria",
    label: "Bulgaria (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/bulgaria.jfif"),
  },
  {
    country: "Canada",
    label: "Canada (CAD $)",
    currencyShort: "CAD $",
    flag: getPublicAssetPath("assets/pages/shopx/languages/canada.jfif"),
  },
  {
    country: "Croatia",
    label: "Croatia (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/croatia.jfif"),
  },
  {
    country: "Cyprus",
    label: "Cyprus (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/cyprus.jfif"),
  },
  {
    country: "Czechia",
    label: "Czechia (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/czechia.jfif"),
  },
  {
    country: "Denmark",
    label: "Denmark (DKK kr.)",
    currencyShort: "DKK kr.",
    flag: getPublicAssetPath("assets/pages/shopx/languages/denmark.jfif"),
  },
  {
    country: "Estonia",
    label: "Estonia (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/estonia.jfif"),
  },
  {
    country: "Finland",
    label: "Finland (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/finland.jfif"),
  },
  {
    country: "France",
    label: "France (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/france.jfif"),
  },
  {
    country: "Germany",
    label: "Germany (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/germany.jfif"),
  },
  {
    country: "Greece",
    label: "Greece (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/greece.jfif"),
  },
  {
    country: "Hungary",
    label: "Hungary (HUF Ft)",
    currencyShort: "HUF Ft",
    flag: getPublicAssetPath("assets/pages/shopx/languages/hungary.jfif"),
  },
  {
    country: "Ireland",
    label: "Ireland (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/ireland.jfif"),
  },
  {
    country: "Italy",
    label: "Italy (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/italy.jfif"),
  },
  {
    country: "Japan",
    label: "Japan (JPY ¥)",
    currencyShort: "JPY ¥",
    flag: getPublicAssetPath("assets/pages/shopx/languages/japan.jfif"),
  },
  {
    country: "Latvia",
    label: "Latvia (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/latvia.jfif"),
  },
  {
    country: "Lithuania",
    label: "Lithuania (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/lithuania.jfif"),
  },
  {
    country: "Luxembourg",
    label: "Luxembourg (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/luxembourg.jfif"),
  },
  {
    country: "Malta",
    label: "Malta (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/malta.jfif"),
  },
  {
    country: "Nethrlands",
    label: "Nethrlands (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/nethrlands.jfif"),
  },
  {
    country: "Poland",
    label: "Poland (PLN zł)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/poland.jfif"),
  },
  {
    country: "Portugal",
    label: "Portugal (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/portugal.jfif"),
  },
  {
    country: "Romania",
    label: "Romania (RON Lei)",
    currencyShort: "RON Lei",
    flag: getPublicAssetPath("assets/pages/shopx/languages/romania.jfif"),
  },
  {
    country: "Singapore",
    label: "Singapore (SGD $)",
    currencyShort: "SGD $",
    flag: getPublicAssetPath("assets/pages/shopx/languages/singapore.jfif"),
  },
  {
    country: "Slovakia",
    label: "Slovakia (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/slovakia.jfif"),
  },
  {
    country: "Slovenia",
    label: "Slovenia (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/slovenia.jfif"),
  },
  {
    country: "Spain",
    label: "Spain (EUR €)",
    currencyShort: "EUR €",
    flag: getPublicAssetPath("assets/pages/shopx/languages/spain.jfif"),
  },
  {
    country: "Sweden",
    label: "Sweden (SEK kr)",
    currencyShort: "SEK kr",
    flag: getPublicAssetPath("assets/pages/shopx/languages/sweden.jfif"),
  },
  {
    country: "Unted Kingdom",
    label: "Unted Kingdom (GBP £)",
    currencyShort: "GBP £",
    flag: getPublicAssetPath("assets/pages/shopx/languages/unted-kingdom.jfif"),
  },
  {
    country: "United States",
    label: "United States (USD $)",
    currencyShort: "USD $",
    flag: getPublicAssetPath("assets/pages/shopx/languages/united-states.jfif"),
  },
];
