import type { LanguageOption } from "../../types/shop-x/shopLanguage.types";
import { getPageAssetURL } from "../../utils/getAssetURL";

export const languageOptions: LanguageOption[] = [
  {
    country: "Italy",
    label: "Italy (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "italy.jfif"),
  },
  {
    country: "Australia",
    label: "Australia (AUD $)",
    currencyShort: "AUD $",
    flag: getPageAssetURL("shopx", "languages", "australia.jfif"),
  },
  {
    country: "Austria",
    label: "Austria (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "austria.jfif"),
  },
  {
    country: "Belgium",
    label: "Belgium (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "belgium.jfif"),
  },
  {
    country: "Bulgaria",
    label: "Bulgaria (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "bulgaria.jfif"),
  },
  {
    country: "Canada",
    label: "Canada (CAD $)",
    currencyShort: "CAD $",
    flag: getPageAssetURL("shopx", "languages", "canada.jfif"),
  },
  {
    country: "Croatia",
    label: "Croatia (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "croatia.jfif"),
  },
  {
    country: "Cyprus",
    label: "Cyprus (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "cyprus.jfif"),
  },
  {
    country: "Czechia",
    label: "Czechia (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "czechia.jfif"),
  },
  {
    country: "Denmark",
    label: "Denmark (DKK kr.)",
    currencyShort: "DKK kr.",
    flag: getPageAssetURL("shopx", "languages", "denmark.jfif"),
  },
  {
    country: "Estonia",
    label: "Estonia (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "estonia.jfif"),
  },
  {
    country: "Finland",
    label: "Finland (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "finland.jfif"),
  },
  {
    country: "France",
    label: "France (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "france.jfif"),
  },
  {
    country: "Germany",
    label: "Germany (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "germany.jfif"),
  },
  {
    country: "Greece",
    label: "Greece (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "greece.jfif"),
  },
  {
    country: "Hungary",
    label: "Hungary (HUF Ft)",
    currencyShort: "HUF Ft",
    flag: getPageAssetURL("shopx", "languages", "hungary.jfif"),
  },
  {
    country: "Ireland",
    label: "Ireland (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "ireland.jfif"),
  },
  {
    country: "Italy",
    label: "Italy (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "italy.jfif"),
  },
  {
    country: "Japan",
    label: "Japan (JPY ¥)",
    currencyShort: "JPY ¥",
    flag: getPageAssetURL("shopx", "languages", "japan.jfif"),
  },
  {
    country: "Latvia",
    label: "Latvia (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "latvia.jfif"),
  },
  {
    country: "Lithuania",
    label: "Lithuania (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "lithuania.jfif"),
  },
  {
    country: "Luxembourg",
    label: "Luxembourg (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "luxembourg.jfif"),
  },
  {
    country: "Malta",
    label: "Malta (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "malta.jfif"),
  },
  {
    country: "Nethrlands",
    label: "Nethrlands (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "nethrlands.jfif"),
  },
  {
    country: "Poland",
    label: "Poland (PLN zł)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "poland.jfif"),
  },
  {
    country: "Portugal",
    label: "Portugal (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "portugal.jfif"),
  },
  {
    country: "Romania",
    label: "Romania (RON Lei)",
    currencyShort: "RON Lei",
    flag: getPageAssetURL("shopx", "languages", "romania.jfif"),
  },
  {
    country: "Singapore",
    label: "Singapore (SGD $)",
    currencyShort: "SGD $",
    flag: getPageAssetURL("shopx", "languages", "singapore.jfif"),
  },
  {
    country: "Slovakia",
    label: "Slovakia (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "slovakia.jfif"),
  },
  {
    country: "Slovenia",
    label: "Slovenia (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "slovenia.jfif"),
  },
  {
    country: "Spain",
    label: "Spain (EUR €)",
    currencyShort: "EUR €",
    flag: getPageAssetURL("shopx", "languages", "spain.jfif"),
  },
  {
    country: "Sweden",
    label: "Sweden (SEK kr)",
    currencyShort: "SEK kr",
    flag: getPageAssetURL("shopx", "languages", "sweden.jfif"),
  },
  {
    country: "Unted Kingdom",
    label: "Unted Kingdom (GBP £)",
    currencyShort: "GBP £",
    flag: getPageAssetURL("shopx", "languages", "unted-kingdom.jfif"),
  },
  {
    country: "United States",
    label: "United States (USD $)",
    currencyShort: "USD $",
    flag: getPageAssetURL("shopx", "languages", "united-states.jfif"),
  },
];
